#version: '3.8' ранее так писали, сейчас этого не требует

services:
  

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=workspace
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    #  - ./init:/init
    #post_start:
     # - command: /bin/bash -c "chmod +x /init/initscript.sh && /init/initscript.sh > /init/tmp.log"
    networks:
      - app-network
        #healthcheck:
        #test: [ "CMD-SHELL", "pg_isready -U postgres -d workspace" ]
        #interval: 10s
        #timeout: 5s
        #retries: 5
        #start_period: 30s
        #restart: unless-stopped
  app:
    #image: go-auth-app:0.1
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/workspace?sslmode=disable
      - JWT_SECRET=MySuperSecretKeyForJWT_2026!
    depends_on:
      - db 
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
